language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3 // match the version used in targetSdk version inside build.gradle
    - android-28
    - android-22
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-21
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support

before_install:
  - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - android list target

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache