language: android
jdk: oraclejdk8
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - android-21
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-21
    # Google Play Services
    - extra-google-google_play_services
branches:
  except:
    - gh-pages

before_install:
  - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
#  - android list target
  - ./gradlew clean installDebug
  - ./gradlew check
  - ./gradlew testDebugUnitTest
  - ./gradlew connectedDebugAndroidTest
